name: 🚀 Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2022
          script: |
            echo "Deploying Next.js app..."

            cd ~ || exit 1

            # Clone repo if it does not exist
            if [ ! -d "social-media-store/frontend/.git" ]; then
              echo "Repository not found. Cloning..."
              git clone git@github.com:thevalicode/social-media-store-frontend.git social-media-store/frontend
            else
              echo "Repository found. Updating..."
            fi

            cd social-media-store/frontend || exit 1

            git reset --hard
            git clean -fd
            git pull origin main

            npm ci --omit=dev
            npm run build

            PORT=4340 pm2 describe social-media-store-frontend > /dev/null \
              && pm2 restart social-media-store-frontend \
              || pm2 start npm --name social-media-store-frontend -- start

            pm2 save

            echo "Deployment completed!"
